### PR TITLE
Feature/code clean up

### PR DESCRIPTION
**Pull request by sir-dunxalot**
This is the first of a couple of PRs I'm hoping to put up. The next will be a functionality PR but this one:
- Fixes browser warnings for the dummy app's CSP
- Cleans up some inconsistent code standards (indentations, `var` and `const`, property order, etc)
- Uses `Ember.on` instead of the component's public methods

Let me know which parts, if any, you'd like to keep. Won't be insulted if you don't want any of it - didn't take much time!

### CODE REVIEW

**Comment by stefanneculai** [comment]
Hi Duncan! Thanks. Would it be possible for you to review this since we made some updates and it is not merge-able anymore.

**Comment by sir-dunxalot** [comment]
Sure thing. Are there any commits you don't want merged in?

**Comment by stefanneculai** [comment]
Let's keep them all.

**Comment by Panman82** [comment]
Thanks for the PR but this addon has been deprecated in favor of [ember-froala-editor](https://github.com/froala/ember-froala-editor).

**Pull request closed without merging**
