### PR TITLE
Used key value pairs to allow period separated methods such as image.Uploaded 

### PR DESCRIPTION
**Pull request by artsmc**
used key value pairs to allow 'SEP' methods where ember is expecting 'EQUAL'.

this should also resolve anyone having issues with methods such as image.Uploaded. I intend on making another pull request updating the documentation.

### CODE REVIEW

**Comment by stefanneculai** [comment]
Hi @artsmc! Thanks for the PR. I believe it would be better to change the way this was implemented initially so that when we add new events the plugin doesn't have to be update. A better approach would be the way this is done in froala-reactive: https://github.com/froala/froala-reactive#options-and-events. 

Could you please make this change? Thank you.

**Comment by artsmc** [comment]
@stefanneculai Yes using _on<event.name> makes sense. But ember is strict about using period separator in property names, I believe it is reserved for property values such as 
{{each event in event.name}} or {{table eventName=event.name}}
This seems to be part of a greater issue with handlebars and being able to use splat operations.
https://github.com/wycats/handlebars.js/issues/1050
Currently the only way I see to make it work dynamically is reverse action and event.
{{event.name="actionName"}} will become {{actionName="on event.name"}}
Thoughts?

**Comment by stefanneculai** [comment]
Could we use underscore _on_event_name and then replace event_name with event.name?

**Comment by artsmc** [comment]
Of course, it's not as pretty as camelCase but it is dynamic. Heck if there was a regex to work on every Froala event I would keep it but the underscore can definitely be dynamic with the exception of the events with arrays such as pop up hide [id] that I'll take just little more tweaking

**Comment by stefanneculai** [comment]
That's great. Thanks!

**Comment by artsmc** [comment]
I'll make the changes and update the readMe, you can see I already added the saveButon concept as well

**Comment by stefanneculai** [comment]
:+1:

**Comment by artsmc** [comment]
its feeling a little lighter and faster

**Comment by stefanneculai** [comment]
Nice work. Thanks.

**Pull request merged**
